model: pretrained/ffhq.pkl
direction: tensor/fs3.npy
input: samples
output: output
neutral: face
targets:
    Width and height of head:
        - Wide face
        - Long face
    Shape and size of eyes:
        - face with Eyes Open
        - face with Narrow Eyes
        - face with Brown Eyes
        - face with Bags Under Eyes
        - face with Eyes Up
        - face with Eyes Down
        - face with Eyes Right
        - face with Eyes Left
    Size and position of eyebrows:
        - face with Arched Eyebrows
        - face with Bushy Eyebrows
        - face with Eyebrows Up
        - face with Eyebrows Down
        - face with Eyebrows Left
        - face with Eyebrows Right
    Size and shape of nose:
        - face with Big Nose
        - face with Pointy Nose
        - face with Nose Up
        - face with Nose Down
        - face with Nose Left
        - face with Nose Right
    Width and height of cheekbones:
        - face with High Cheekbones
        - face with Wide Cheekbones
    Width and shape of the jaw:
        - face with Round Jaw
        - face with Wide Jaw
    Shape and size of the lips:
        - face with Big Lips
    Length and shape of the chin:
        - face with Double Chin
    Profile of the forehead and jaw:
        - Bald face
        - Chubby face
    Skin color:
        - Asian face
        - White face
        - Black face
        - Indian face
        - face with Pale Skin
        - face with Shiny Skin
        - face with Rosy Cheeks
    Hair:
        - face with Black Hair
        - face with Blond Hair
        - face with Brown Hair
        - face with Gray Hair
        - face with Curly Hair
        - face with Straight Hair
        - face with Wavy Hair
        - face with Receding Hairline
        - face with Bangs
    Makeup:
        - face with Heavy Makeup
        - face with Lipstick
    Facial expressions:
        - Surprised face
        - Fearful face
        - Disgusted face
        - Happy face
        - Sad face
        - Angry face
        - Frowning face
        - Smiling face
    Position of the mouth and lips:
        - face with Mouth Closed
        - face with Mouth Slightly Open
        - face with Mouth Wide Open
    Face shapes:
        - Oval Face
        - Square Face
        - Round Face
    Age:
        - Baby face
        - Child face
        - Middle Aged face
        - Senior face
        - Youth face
    Beard:
        - face with Beard
        - face with No Beard
        - face with Mustache
        - face with Goatee
    Lightning:
        - face under Harsh Lighting
        - face under Flash Lighting
    Accessories:
        - face with Earrings
        - face with Hat
        - face with Necklace
        - face with Necktie
        - face with Eyeglasses
        - face with Sunglasses
    Other:
        - Attractive face
        - Blurry face
        - face with Sideburns
alpha: [ -5,5,0.01 ]
beta: 0.1
size: [ 256,256 ]